version: '3.8'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./task_management.db
      - SECRET_KEY=please-change
    volumes:
      - ./:/app
